# {{PROYECTO}} | Odoo {{ODOO_VERSION}} | generado por omc (ejemplo: copiar a .env y completar)
ENTORNO={{ENTORNO}}
ODOO_VERSION={{ODOO_VERSION}}
ODOO_IMAGE={{ODOO_IMAGE}}
POSTGRES_IMAGE={{POSTGRES_IMAGE}}
POSTGRES_PASSWORD=cambiar-esta-clave
ODOO_PORT={{ODOO_PORT}}
ODOO_GEVENT_PORT={{ODOO_GEVENT_PORT}}
PG_SHARED_BUFFERS={{PG_SHARED_BUFFERS}}
PG_EFFECTIVE_CACHE={{PG_EFFECTIVE_CACHE}}
PG_WORK_MEM={{PG_WORK_MEM}}
PG_MAINT_MEM={{PG_MAINT_MEM}}
PG_MAX_CONN={{PG_MAX_CONN}}
ODOO_CPUS={{ODOO_CPUS}}
ODOO_MEM={{ODOO_MEM}}
DB_CPUS={{DB_CPUS}}
DB_MEM={{DB_MEM}}
